import Header from "@/components/shared/Header";
import type { Metadata } from "next";
import { Geist, Montserrat } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Montserrat({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-medium ${geistMono.variable}`}>
        <div className="h-screen w-screen bg-[#181818]">
          <header>
            <Header />
          </header>
          <main className="px-10 mt-10 max-md:px-5">{children}</main>
        </div>
      </body>
    </html>
  );
}
